---
title: ""
author: Brendan Graham
date: '2022-02-08'
slug: airmen
categories: 
tags:
subtitle: 
summary: 'This post looks at a [TidyTuesday](https://github.com/rfordatascience/tidytuesday) data set about'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
draft: true 
editor_options: 
  chunk_output_type: console
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = T, fig.height = 7, fig.width = 9, message = FALSE, warning = FALSE)

options(scipen = 100)
options(tidymodels.dark = TRUE) 

library(tidytuesdayR)
library(tidyverse)
library(lubridate)
library(highcharter)
library(plotly)
library(purrr)
library(skimr)
library(here)
library(ggrepel)
library(tidymodels)
library(rules)
library(vetiver)
library(doParallel)
library(pins)
library(ggsci)
library(statebins)

round_numerics <- 
  function(data, digits = 2){
    data %>%
      mutate(across(where(is.numeric), ~ round(.x, digits)))
  }

add_table <- 
  function(data){
    data %>%
      round_numerics() %>%
      reactable::reactable(., fullWidth = F, resizable = T, filterable = T, 
                           highlight = T, defaultPageSize = 10, wrap = FALSE,
                           showSortIcon = T, striped = T, compact = T)
  }

bg_theme <- 
  function(base_size = 11,
           strip_text_size = 12,
           strip_text_margin = 10,
           subtitle_size = 13,
           subtitle_margin = 10,
           plot_title_size = 16,
           plot_title_margin = 10,
           font = "RobotoMono-Regular",
           ...) {
    
    ret <-
      ggplot2::theme_gray(base_family = font,
                          base_size = base_size, ...,) +
      theme(
        panel.background = element_rect(fill = "#e9e9ea"),
        plot.background = element_rect(fill = "#f3f3f3"),
        legend.background = element_rect(fill = "#f3f3f3"),
        panel.grid = element_line(color = "#ffffff"),
        panel.grid.major = element_line(color = "#ffffff")
        )
    
    ret$strip.text <-
      ggplot2::element_text(
        # hjust = 0,
        vjust = -.8,
        size = strip_text_size,
        margin = ggplot2::margin(b = strip_text_margin),
        family = font
      )
    
    ret$plot.subtitle <-
      ggplot2::element_text(
        hjust = 0,
        size = subtitle_size,
        margin = ggplot2::margin(b = subtitle_margin),
        family = font
      )
    
    ret$plot.title <-
      ggplot2::element_text(
        hjust = 0,
        size = plot_title_size,
        margin = ggplot2::margin(b = plot_title_margin),
        family = font
      )
    
    ret
  }

bg_red <- "#E64B35"
bg_green <- "#00a087"
bg_blue <- "#4DBBD5"

airmen <- 
  readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-08/airmen.csv')

```


```{r}

airmen %>%
  add_table 

skimr::skim_to_list(airmen)

```

```{r}

airmen %>% 
  group_by(state) %>% 
  tally(sort = T) %>%
  na.omit() %>%
  mutate(freq = n / sum()) %>%
  ggplot(aes(x = reorder(state, n), y = n, label = n)) + 
  geom_col(fill = bg_green, alpha = .75) + 
  coord_flip() + 
  scale_y_continuous(expand = c(0, 1)) + 
  bg_theme() 

airmen %>% 
  mutate(grad_year = year(as.Date(graduation_date))) %>% 
  group_by(grad_year) %>% 
  tally(sort = T) %>%
  ggplot(aes(x = factor(grad_year), y = n, label = n)) + 
  geom_line(color = bg_green, alpha = .75, group = 1) + 
  geom_point(color = bg_green, alpha = .75) + 
  bg_theme() +
  labs(x = 'year', y = "total grads")

airmen %>% 
  group_by(pilot_type) %>% 
  tally(sort = T) %>%
  na.omit() %>%
  mutate(freq = n / sum()) %>%
  ggplot(aes(x = reorder(pilot_type, n), y = n, label = n)) + 
  geom_col(fill = bg_green, alpha = .75) + 
  coord_flip() + 
  scale_y_continuous(expand = c(0, 10)) + 
  bg_theme() 

airmen %>% 
  mutate(rank_group = ifelse(!rank_at_graduation %in% c("2nd Lt", "1st Lt", "Flight Officer"), "other", rank_at_graduation)) %>%
  group_by(pilot_type, rank_group) %>% 
  tally(sort = T) %>%
  na.omit() %>%
  ggplot(aes(x = reorder(pilot_type, n), y = n, fill = rank_group)) + 
  geom_col(alpha = .75, show.legend = FALSE) + 
  coord_flip() + 
  bg_theme() +
  scale_fill_npg() +
  facet_wrap(vars(rank_group), scales = 'free')

adat <- read_csv(system.file("extdata", "wapostates.csv", package="statebins"))

state_totals <- 
  airmen %>% 
  group_by(state) %>% 
  tally(sort = T) %>%
  left_join(., adat %>% select(stab, state_name = state), by = c("state" = "stab"))

statebins(state_totals %>% ungroup() %>% select(state = state_name, n) %>% as.data.frame(), 
          value_col = "n",
          state_col = "state",
          palette = "Purples",
          round = T) +
  labs(x="2008-2010") +
  theme_statebins(legend_position = "none") 

```




